### ISSUE TITLE
RC npm: "hash pinning" is a confusing term

### ISSUE THREAD

**Issue by ljharb** [ossf/package-manager-best-practices#9]
I've never heard this term in this context before. The way it's described in the npm ecosystem is "using a lockfile".

**Comment by mlieberman85** [comment]
It is defined in the document. I think hash or checksum pinning is fairly common in the broader package ecosystem where this might still make sense to define here as it's fairly common, just perhaps outside the npm ecosystem.

Do you have better terminology that might be more familiar to the npm community we can use in order to make it clear that what's important is the `integrity` value is the hash or checksum of the package you are intending to download?

**Comment by ljharb** [comment]
That's what a lockfile is - it wouldn't really be one without built-in integrity checking, would it?

**Comment by ljharb** [comment]
Either way, the target audience here is the npm community - non-npm folks don't need to understand the "npm best practices" document :-)

**Comment by mlieberman85** [comment]
I disagree. I think generally consumers of a thing also want to know that people are largely following best practices and how to verify those best practices. Also, it's intended to help people better understand general security and apply it to production/consumption of npm

**Comment by ljharb** [comment]
I don't mean to suggest that the term shouldn't appear; i mean to suggest that it shouldn't be the primary one used.

**Comment by lirantal** [comment]
I agree with Jordan that this is a term that's not particularly common or known in the JavaScript package ecosystem.

To better understand though, are we really saying "use a lockfile" as part of this best practice, or are we actually referring to the hash? the lockfile is more than just the hash too.

**Comment by ljharb** [comment]
The best practice should be (and is) "use a lockfile".

**Comment by lirantal** [comment]
100%, I'm just wondering whether there has been a bigger thing here that @mlieberman85 was trying to address.

There are also security concerns with lockfile injection and tampering which should be addressed as best practices, and this one doesn't cover.

**Comment by mlieberman85** [comment]
> I don't mean to suggest that the term shouldn't appear; i mean to suggest that it shouldn't be the primary one used.

That makes sense. Would changing the heading to "Use a Lockfile" and underneath it explain that the reasoning is it does "hash pinning" which allows you to enforce that you don't pull in anything but what was captured when you generated the lockfile, be clearer?

**Comment by ljharb** [comment]
@mlieberman85 yes, much clearer, because virtually every person in the npm ecosystem won't know or care about the term "hash pinning", but "use a lockfile" will be straightforward.

**Comment by david-a-wheeler** [comment]
Saying "use a lockfile" is fine as long as the lockfile includes, for each package, the "integrity" value that contains a strong cryptographic hash. As far as I know lockfiles always include integrity values, but there is a related problem...

In practice a lot of them use SHA-1, which is a big problem because SHA-1 is broken. E.g., you might see "integrity": "sha1-ml9pkFGx5wczKPKgCJaLZOopVdI=" if you use array-flatten version 1.1.1.

I think there should be encouragement to move *away* from SHA-1 (at least as the ONLY integrity value). Not sure how to word that.

Note that SHA-512 is fine. E.g., the integrity value "sha512-hIP3EEPs8tB9AT1L+NUqtwOAps4mk2Zob89MWXMHjHWg9milF/j4osnnQLXBCBFBk/tvIG/tUc9mOUJiPBhPXA==" you'd get from "content-type" version 1.0.4 is just fine.

**Comment by ljharb** [comment]
yes, i think if there's no integrity hash it's not much of a lockfile :-)

I'm pretty sure that npm always uses sha-512 whenever the system supports it, and whenever the package was published recently enough that a sha512 hash exists. It'd be a great [RFC](https://github.com/npm/rfcs) to suggest a config (assuming none exists) to require sha512 hashes.

**Comment by david-a-wheeler** [comment]
I would say the top statement should be "Use a lockfile", and somewhere in its rationale explain why. Something like:

> Use a lockfile because it implements hash pinning using cryptographic hashes. "Hash pinning" means that *any* change to the package will be immediately rejected, so any malicious change to the dependency would be detected and rejected. Note that historically the SHA-1 algorithm was used for hash pinning, but that algorithm has been broken. Where possible, don't use SHA-1 and instead use secure algorithms (such as SHA-512).

Feel free to modify, that's just a potential starting point. But we should always *justify* doing something, and if there's a gotcha/warning, tell them. If there's an easier to way to force the use of SHA-512 (or something secure instead of SHA-1) that'd be even better...!
